import Link from "next/link";
import {
  ArrowUpRight,
  BookOpenCheck,
  BrainCircuit,
  ChevronRight,
  Clock3,
  FileText,
  Headphones,
  MessageSquareText,
  Sparkles,
  Trophy,
  UserRoundPlus,
  UsersRound,
} from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { StatusPill } from "@/components/status-pill";
import { getOverviewData, type ActivityItem } from "@/lib/data";
import { formatCompact, formatDate, formatDuration } from "@/lib/format";

export const metadata = { title: "Overview" };
export const dynamic = "force-dynamic";

const activityIcons = {
  session: MessageSquareText,
  topic: Sparkles,
  quiz: Trophy,
  voice: Headphones,
};

function ActivityIcon({ kind }: { kind: ActivityItem["kind"] }) {
  const Icon = activityIcons[kind] ?? Clock3;
  return <Icon size={17} />;
}

export default async function DashboardPage() {
  const { stats, trends, activity, subjects } = await getOverviewData();
  const maxTrend = Math.max(...trends.flatMap((day) => [day.sessions, day.topics, day.quizzes]), 1);
  const maxSubject = Math.max(...subjects.map((item) => item.count), 1);
  const todayLabel = new Intl.DateTimeFormat("en-IN", {
    weekday: "long",
    day: "numeric",
    month: "long",
    timeZone: "Asia/Kolkata",
  }).format(new Date());

  return (
    <main>
      <div className="page-heading">
        <div>
          <p className="eyebrow">{todayLabel}</p>
          <h1>Good evening.</h1>
          <p>Here&apos;s how Odhu Indhu is moving today.</p>
        </div>
        <span className="system-health"><i /> All systems normal</span>
      </div>

      <section className="metric-grid" aria-label="Key metrics">
        <article className="metric-card featured">
          <div className="metric-icon"><UsersRound size={20} /></div>
          <div className="metric-label">Total learners</div>
          <div className="metric-value">{formatCompact(stats.users)}</div>
          <p><UserRoundPlus size={14} /> {stats.new_users_7d} joined this week</p>
        </article>
        <article className="metric-card">
          <div className="metric-icon amber"><BookOpenCheck size={20} /></div>
          <div className="metric-label">Study sessions</div>
          <div className="metric-value">{formatCompact(stats.sessions)}</div>
          <p><ArrowUpRight size={14} /> {stats.sessions_7d} in the last 7 days</p>
        </article>
        <article className="metric-card">
          <div className="metric-icon blue"><Clock3 size={20} /></div>
          <div className="metric-label">Study time</div>
          <div className="metric-value">{formatDuration(stats.study_minutes)}</div>
          <p>{stats.topics} topic sets generated</p>
        </article>
        <article className="metric-card">
          <div className="metric-icon violet"><Trophy size={20} /></div>
          <div className="metric-label">Quiz attempts</div>
          <div className="metric-value">{formatCompact(stats.quizzes)}</div>
          <p>{stats.average_score === null ? "No scores yet" : `${stats.average_score} average score`}</p>
        </article>
      </section>

      <section className="overview-grid">
        <article className="panel activity-panel">
          <div className="panel-heading">
            <div><h2>Activity</h2><p>Sessions, topics and quizzes over the last week</p></div>
            <Link href="/dashboard/learning">View learning <ChevronRight size={15} /></Link>
          </div>
          <div className="chart-legend">
            <span><i className="legend-green" /> Sessions</span>
            <span><i className="legend-amber" /> Topics</span>
            <span><i className="legend-ink" /> Quizzes</span>
          </div>
          <div className="trend-chart" aria-label="Seven day activity chart">
            {trends.map((point) => (
              <div className="trend-day" key={point.day}>
                <div className="trend-bars">
                  <i className="bar-session" style={{ height: `${Math.max((point.sessions / maxTrend) * 100, point.sessions ? 8 : 2)}%` }} title={`${point.sessions} sessions`} />
                  <i className="bar-topic" style={{ height: `${Math.max((point.topics / maxTrend) * 100, point.topics ? 8 : 2)}%` }} title={`${point.topics} topics`} />
                  <i className="bar-quiz" style={{ height: `${Math.max((point.quizzes / maxTrend) * 100, point.quizzes ? 8 : 2)}%` }} title={`${point.quizzes} quizzes`} />
                </div>
                <span>{new Intl.DateTimeFormat("en-IN", { weekday: "short", timeZone: "Asia/Kolkata" }).format(new Date(`${point.day}T12:00:00+05:30`))}</span>
              </div>
            ))}
          </div>
        </article>

        <article className="panel subject-panel">
          <div className="panel-heading"><div><h2>Topic mix</h2><p>Generated by subject</p></div></div>
          {subjects.length ? (
            <div className="subject-list">
              {subjects.map((subject) => (
                <div key={subject.subject}>
                  <span><strong>{subject.subject}</strong><small>{subject.count}</small></span>
                  <div><i style={{ width: `${Math.max((subject.count / maxSubject) * 100, 6)}%` }} /></div>
                </div>
              ))}
            </div>
          ) : <EmptyState title="No topics yet" detail="Generated topic sets will appear here." />}
        </article>
      </section>

      <section className="overview-grid bottom-grid">
        <article className="panel recent-panel">
          <div className="panel-heading">
            <div><h2>Recent activity</h2><p>The latest learner and processing events</p></div>
          </div>
          {activity.length ? (
            <div className="activity-list">
              {activity.map((item) => (
                <div className="activity-row" key={`${item.kind}-${item.id}`}>
                  <span className={`activity-icon ${item.kind}`}><ActivityIcon kind={item.kind} /></span>
                  <span className="activity-copy"><strong>{item.title}</strong><small>{item.subtitle}</small></span>
                  <StatusPill status={item.status} />
                  <time>{formatDate(item.occurred_at, true)}</time>
                </div>
              ))}
            </div>
          ) : <EmptyState title="Nothing to show yet" detail="New learning activity will appear here." />}
        </article>

        <article className="panel pulse-panel">
          <div className="panel-heading"><div><h2>Weekly pulse</h2><p>Output pipeline</p></div></div>
          <div className="pulse-stack">
            <div><span className="pulse-icon"><FileText size={18} /></span><span><strong>{stats.reports}</strong><small>Reports generated</small></span></div>
            <div><span className="pulse-icon amber"><Headphones size={18} /></span><span><strong>{stats.voice_notes}</strong><small>Voice notes</small></span></div>
            <div><span className="pulse-icon violet"><BrainCircuit size={18} /></span><span><strong>{stats.topics}</strong><small>Topic sets</small></span></div>
          </div>
          <Link className="panel-cta" href="/dashboard/operations">Open operations <ArrowUpRight size={15} /></Link>
        </article>
      </section>
    </main>
  );
}
